name: Calculate & Update Line of Code

on:
  workflow_dispatch

jobs:
  calculate-line-of-code:
    name: Calculate Line of Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token # Needs 'repo' scope

      - name: Get User Repositories
        id: get_repos
        run: |
          gh repo list "galaniyati" --limit 1000 --json nameWithOwner --jq '.[].nameWithOwner' > repos.txt
          cat repos.txt
      - name: Analyze LOC for Each Repo
        run: |
          aggregated_loc_by_language=$(yq -n)
          while IFS= read -r repo_with_owner; do
            owner=$(echo "$repo_with_owner" | cut -d'/' -f1)
            repo=$(echo "$repo_with_owner" | cut -d'/' -f2)

            echo "Analyzing LOC for $repo_with_owner"

            # Clone the repository
            git clone "https://github.com/$repo_with_owner.git" "$repo"

            # Inline LOC analysis script logic
            loc_data=$(git log --author="${{ github.event.inputs.username || github.repository_owner }}" --pretty=tformat: --numstat --since="1970-01-01T00:00:00Z" "$repo" |
              awk '
                NF == 3 { added += $1; deleted += $2; split($3, parts, "."); if (length(parts) > 1) { lang = parts[length(parts)]; lang_added[lang] += $1; lang_deleted[lang] += $2 } }
                END {
                  printf "language_loc:\n"
                  for (l in lang_added) {
                    loc = lang_added[l] - lang_deleted[l]
                    if (loc != 0) {
                      printf "  %s: %d\n", l, loc
                    }
                  }
                }
              ')

            if [ -n "$loc_data" ]; then
              aggregated_loc_by_language=$(echo "$aggregated_loc_by_language" | yq -M ". * ($loc_data)")
            fi

            # Clean up
            cd ..
            rm -rf "$repo"
          done < repos.txt

          echo "$aggregated_loc_by_language" > total_loc_by_language.yaml
          echo "$aggregated_loc_by_language" 

