name: Create labels
on: 
  workflow_dispatch:
    inputs:
      user_confirmation:
        description: Enter the repository name
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Workflow triggered manually! ${{ toJson(github.event.inputs) }}"
      - name: Print Value
        run: echo "Value! ${{ github.event.inputs.user_confirmation }}"
      - name: create label
        run: gh label create "testing" --repo ${{ github.event.inputs.user_confirmation }} --color FF0000 --description "Issues related to testing"
        env:
          GH_TOKEN: ${{ github.token }}
          
